
DROP TABLE IF EXISTS 'users';

CREATE TABLE users(
	ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	email VARCHAR(40) NOT NULL UNIQUE,
	pass CHAR(40) NOT NULL,
	token CHAR(40) NOT NULL DEFAULT "5dc9b72fbcef651e31ff0b484117b119e17acebd",
	user_rol enum("normal", "god") NOT NULL DEFAULT "normal",
	name VARCHAR(40) NOT NULL,
	first_name VARCHAR(60),
	DNI CHAR(9) NOT NULL UNIQUE,
	phone VARCHAR(15),
	city VARCHAR(50),
	CP VARCHAR(10) NOT NULL,
	avatar VARCHAR(500),
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS 'clubs';

CREATE TABLE clubs(
	ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_user INT(10),
	name VARCHAR(40) NOT NULL,
	phone VARCHAR(15),
	email VARCHAR(50),
	address VARCHAR(80),
	city VARCHAR(50) NOT  NULL,
	state VARCHAR(50),
	CP VARCHAR(10),
	country VARCHAR(50),
	servicios VARCHAR(500),
	gps VARCHAR(100),
	logo VARCHAR(400),
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FOREIGN KEY (ID_user) REFERENCES users(ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS 'courts';

CREATE TABLE courts(
	ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_club INT(10) NOT NULL,
	name VARCHAR(40) NOT NULL,
	court_number INT(3) NOT NULL,
	type enum("indoor", "outdoor", "cubierta") NOT NULL DEFAULT "outdoor",
	size enum("individual", "dobles") NOT NULL DEFAULT "dobles",
	estructure enum("cristal", "muro", "panorámica") NOT NULL DEFAULT "cristal",
	photo VARCHAR(400) DEFAULT ("http://localhost:3001/media/logo-padel-alcala.png"),
	start_hour INT(4) NOT NULL DEFAULT 0,
	end_hour INT(4) NOT NULL DEFAULT 1440,
	CONSTRAINT FOREIGN KEY (ID_club) REFERENCES clubs(ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS 'bookings';

CREATE TABLE bookings(
	ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_user INT(10) NOT NULL,
	ID_court INT(10) NOT NULL,
	start_time DATETIME NOT NULL,
	end_time DATETIME NOT NULL,
	CONSTRAINT FOREIGN KEY (ID_user) REFERENCES users(ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ID_court) REFERENCES courts(ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS 'favorites';

CREATE TABLE favorites(
	ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_user INT(10) NOT NULL,
	ID_club INT(10) NOT NULL,
	CONSTRAINT FOREIGN KEY (ID_user) REFERENCES users(ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ID_club) REFERENCES clubs(ID) ON DELETE CASCADE
);